### ISSUE TITLE
What are your Github usernames?

### ISSUE THREAD

**Issue by phillipadsmith** [hackshackers/action-group-website#1]
Can you drop a comment here so that I have your usernames and can add you to this repo? Thanks! :)

**Comment by monkeycycle** [comment]
Check 1 2.

**Comment by phillipadsmith** [comment]
@monkeycycle Are you joining our little Action Group!? **Amazing!** :+1:

**Comment by burtherman** [comment]
Happy to be kept in the loop here too!

**Comment by phillipadsmith** [comment]
@burtherman Super. That's the idea! :) 

Also, I'm hoping that @macdiva or @burtherman can create a Github team just for this website action group (or give me the power to do so!). 

Let me know!

**Comment by monkeycycle** [comment]
YES! If you’ll have me. 

Michael

# 

Michael Pereira
monkeycycle@gmail.com

m: 416 821 5081
t:  monkeycycle_org

PGP: C5AD 6FA0 628C 2847 DCA4 D84A 1027 7A0E 8D8B 1279
http://bit.ly/1POTohN

**Comment by thomaswilburn** [comment]
Well, mine's easy enough.

**Comment by burtherman** [comment]
@phillipadsmith I created a team for you with admin access ...

**Comment by phillipadsmith** [comment]
@burtherman :100:

**Comment by phillipadsmith** [comment]
@monkeycycle  Yep, we sure will. I'll invite you to our first Google Hangout next week.

**Comment by phillipadsmith** [comment]
Hi Folks,

Just a quick reminder that we're going to have a quick Google Hangout tomorrow at 1PM Pacific / 4PM Eastern for 30 minutes. The link should be in your Google Calendar. If you don't have it, please shout. :)

The agenda is roughly:
- Find agreement on our action group's scope of work
- Draft a  small list of tasks that need to be undertaken to move this group's work forward

Please add to the agenda if you have other items that you'd like to discuss. 

Cheers,

Phillip.

**Comment by monkeycycle** [comment]
Hey Phillip  ~ 

I don’t see the link in my calendar, can you send it my way? 

thanks,
Michael

# 

Michael Pereira
monkeycycle@gmail.com

m: 416 821 5081
t:  monkeycycle_org

PGP: C5AD 6FA0 628C 2847 DCA4 D84A 1027 7A0E 8D8B 1279
http://bit.ly/1POTohN

**Comment by jakubgornicki** [comment]
@jakubgornicki Hi!
