### ISSUE TITLE
Quick, 30-minute call to discuss next steps for Website proposal

### ISSUE THREAD

**Issue by phillipadsmith** [hackshackers/action-group-website#11]
Howdy @hackshackers/action-group-website 

So, we've got a fair bit of data.

Shall we have another quick call to outline some next steps toward making a recommendation? 

I've proposed some dates here:
http://whenisgood.net/bktyn43

I believe our last call was at 1PM PT / 4PM ET and might propose the same if that works.

Let me know what works for you all: 
http://whenisgood.net/bktyn43

**Comment by phillipadsmith** [comment]
The results are in! 

Event:  Hacks/Hackers Website Action Group
Date:   November 18, 2015
Can make it:    Burt, Misha, Thomas Wilburn

So, let's plan for a 30-minute conversation at 1PM PT / 4PM ET on Calliflower (you'll get a notification on that momentarily).

If there's anyone else who can make it, please drop a note here and I'll add you to the call.

Phillip.

cc @hackshackers/action-group-website

**Comment by phillipadsmith** [comment]
Actually, just a note that I've set this call to "open" -- so anyone can join at the following link: http://bit.ly/1PG6yOg

**Comment by phillipadsmith** [comment]
Hey @samanthasunne! Would you be able to join us on Wednesday? See above for context. :-)

**Comment by samanthasunne** [comment]
Yes! I will be there
