### ISSUE TITLE
Alley Interactive proposal

### ISSUE THREAD

**Issue by phillipadsmith** [hackshackers/action-group-website#14]
Dear @hackshackers/action-group-website members,

Please find attached a formal proposal from Alley Interactive.

The timeline on this proposal is roughly as follows:
- There have been ongoing discussions between Burt and Amanda (both H/H SF chapter organizers) about having Alley work on a new hackshackers.com web property
- Amanda re-iterated Alley's interest in working on the site at Connect SF (Jan '16) and I had subsequent conversations with Austin at Connect NYC (Feb '16). 
- Alley was advised of the request for expressions of interest and let me know by e-mail that they were interested prior to the deadline, but asked for an opportunity to discuss the project in more detail before submitting a proposal.

Thus, I consider this a good faith proposal in terms of the timing of its receipt.

Austin's casual comment in the e-mail with the proposal attached was "tl;dr, good to do this in-kind if you'll let us do the logo. thanks!"

The thrust of the proposal is for Alley to undertake a full-scale re-design of the H/H branding and web property. They would provide their services in-kind for a "long-term exclusive digital sponsorship of the site itself, to be mutually agreed upon acceptance of this proposal." That is further clarified as:

> We would not propose anything that would demean Hacks/Hackers or Alley — likely a simple “designed by” graphic in the site footer, a mention in the “about” page, and coordinated launch marketing."

Given my personal relationship with both of the two companies/individuals submitting proposals -- Alley and Misha -- I do not feel comfortable making a decision on this without the input from the other members of the action group.

I am going to be on route to France during the global call today. I am hoping that another member of the action group could present these two options on the call. Any takers? 

Best,

Phillip. 

[alley and hacks+hackers.pdf](https://github.com/hackshackers/action-group-website/files/302083/alley.and.hacks.hackers.pdf)

**Comment by Cromian** [comment]
@hackshackers/action-group-website I am going to jump in and say lets go with Alley. Alley has more resources and talent. Not saying I am not interested, nor would my work be sub-par, but if they are willing to do this pro-bono with a commitment that all code, images, and assets are open-sourced this is a win for H/H. I only submitted a proposal b/c at the time I could not do a project of this scale pro-bono nor have we received an RFP. @burtherman @phillipadsmith thoughts?

**Comment by samanthasunne** [comment]
The Alley proposal certainly seems thorough. Especially with Misha’s comment, I’m willing to endorse their plan, but with a couple of concerns:

I’d like to know exactly what they would be getting in exchange for this pro bono work. What does “long-term exclusive digital sponsorship” mean? Considering they’d be spending $83k on this project, we should hammer out what they’re expecting in return, and have it in writing before they begin.

Also, it looks like they plan to completely overhaul the logo, branding, etc. - no more black&white Hacks/Hackers banner. I don’t have any quarrel with this, but I wanted to bring it to everyone’s attention since it’s outside the scope of the original project (updating the website).

**Comment by burtherman** [comment]
@Cromian Thanks for your endorsement on this, that's kind of you to say and much appreciated. It seems like a win for everyone to have their larger team on this and to have it all open sourced.

@samanthasunne Great points you make. We should indeed clarify on the sponsorship and get that in writing. As far as the branding overhaul, I think the idea is for something subtle. The original was put together pretty quickly so this would be an update to keep it fresh while keeping the spirit of how things have been in the past.

**Comment by phillipadsmith** [comment]
@Cromian @samanthasunne @burtherman Given your comments here, what would you all propose are the next steps? And who should move them forward? I'll take a shot:
- [ ] Communicate to Alley that we're supportive of moving forward with their proposal
- [ ] Ask for clarification on the branding undertaking
- [ ] Ask for clarification on the "sponsorship" language on the site

**Comment by burtherman** [comment]
This sounds like a fine plan to me, and it would be good to be able to have
these things clarified and the proposal in motion before the next open
global call, to put a timeframe on this. I'm happy to also be involved in
moving this forward ASAP

On Thu, Jun 23, 2016 at 4:10 PM, Phillip Smith notifications@github.com
wrote:

> @Cromian https://github.com/Cromian @samanthasunne
> https://github.com/samanthasunne @burtherman
> https://github.com/burtherman Given your comments here, what would you
> all propose are the next steps? And who should move them forward? I'll take
> a shot:
> - Communicate to Alley that we're supportive of moving forward with
>   their proposal
> - Ask for clarification on the branding undertaking
> - Ask for clarification on the "sponsorship" language on the site
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/hackshackers/action-group-website/issues/14#issuecomment-228168775,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAIH8fpNuBFtgz2GghJyzhH6adeqlQjGks5qOugfgaJpZM4IvqnW
> .

## 

Burt Herman
http://burtherman.com
@burtherman
+16504538787

**Comment by phillipadsmith** [comment]
> This sounds like a fine plan to me, and it would be good to be able to have
> these things clarified and the proposal in motion before the next open
> global call, to put a timeframe on this. 

Tuesday, July 2nd.

> I'm happy to also be involved in moving this forward ASAP

Would you be open to conveying the above to Alley?

**Comment by burtherman** [comment]
Yes, I can convey above to Alley. Is Amanda our main contact, or also
Austin on this?

On Thu, Jun 23, 2016 at 5:07 PM, Phillip Smith notifications@github.com
wrote:

> This sounds like a fine plan to me, and it would be good to be able to have
> these things clarified and the proposal in motion before the next open
> global call, to put a timeframe on this.
> 
> Tuesday, July 2nd.
> 
> I'm happy to also be involved in moving this forward ASAP
> 
> Would you be open to conveying the above to Alley?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/hackshackers/action-group-website/issues/14#issuecomment-228184204,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAIH8fBk_WQqgbrpCgNfjsddsJ--CIkJks5qOvWegaJpZM4IvqnW
> .

## 

Burt Herman
http://burtherman.com
@burtherman
+16504538787

**Comment by phillipadsmith** [comment]
Both.

**Comment by samanthasunne** [comment]
Just chiming in to say this plan sounds good to me. I'd like to get the
rebranding and "in-kind" agreements carefully in writing before actually
signing a contract.

**Comment by burtherman** [comment]
Great, can you cc me into the thread there with them where they sent the
proposal?

On Thu, Jun 23, 2016 at 6:05 PM, Phillip Smith notifications@github.com
wrote:

> Both.
> 
> > On Jun 23, 2016, at 5:52 PM, Burt Herman notifications@github.com
> > wrote:
> > 
> > Yes, I can convey above to Alley. Is Amanda our main contact, or also
> > Austin on this?
> > 
> > On Thu, Jun 23, 2016 at 5:07 PM, Phillip Smith <notifications@github.com
> > 
> > wrote:
> > 
> > > This sounds like a fine plan to me, and it would be good to be able to
> > > have
> > > these things clarified and the proposal in motion before the next open
> > > global call, to put a timeframe on this.
> > > 
> > > Tuesday, July 2nd.
> > > 
> > > I'm happy to also be involved in moving this forward ASAP
> > > 
> > > Would you be open to conveying the above to Alley?
> > > 
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > <
> > > https://github.com/hackshackers/action-group-website/issues/14#issuecomment-228184204
> > > ,
> > > or mute the thread
> > > <
> > > https://github.com/notifications/unsubscribe/AAIH8fBk_WQqgbrpCgNfjsddsJ--CIkJks5qOvWegaJpZM4IvqnW
> > > 
> > > .
> > 
> > ## 
> > 
> > Burt Herman
> > http://burtherman.com
> > @burtherman
> > +16504538787
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub <
> > https://github.com/hackshackers/action-group-website/issues/14#issuecomment-228196113>,
> > or mute the thread <
> > https://github.com/notifications/unsubscribe/AACFUISri3M4fuKDyNmcKo5xKrjxb93Mks5qOwA5gaJpZM4IvqnW
> > .
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/hackshackers/action-group-website/issues/14#issuecomment-228199512,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAIH8abzT0Q5hJOHhtd9mjrtrMQ7QPhxks5qOwNBgaJpZM4IvqnW
> .

## 

Burt Herman
http://burtherman.com
@burtherman
+16504538787

**Comment by phillipadsmith** [comment]
> Great, can you cc me into the thread there with them where they sent the
> proposal?

Done.

**Comment by burtherman** [comment]
Here's the reply from Alley on the questions, FYI:

Branding: Modernization, not anything deeper. Might extend to a substantively new logo, but would certainly provide really standardized treatments for your brand identity in the style guide we create. A core deliverable here is a "style tile toolbox" which anyone who knows HTML can use to build on-brand digital stuff.

Sponsorship: We'd just want mentions in launch publicity and a link at the bottom of each page. Something along the lines of "Designed and built by Alley Interactive and the Hacks/Hackers Community" with a link to our site.

We also expect to be informal stewards of the transition to community maintenance; ongoing participation in this process will be a good way for us to actually demonstrate our value as either an employer for them personally or a consultant for their day-job organizations to your community. So simply by doing our jobs well we'll achieve some marketing value.

**Comment by samanthasunne** [comment]
Sorry for my late response. Since Alley is really our only option, I say
let's go ahead and do it. I just wanted to do some due diligence on this
proposal, and their "in-kind" requests seem reasonable. Let's go ahead and
draw up a contract, and let me know if you want any help from my end.
