### ISSUE TITLE
Post one question that you would like to ask organizers, members, and interested parties

### ISSUE THREAD

**Issue by phillipadsmith** [hackshackers/action-group-website#2]
So, our collective TODO item -- due before Wednesday, September 30th -- is to post one (or more, but at least one) question that we would like to ask other Hacks/Hackers organizers, members, and interested parties.

We'll collect the questions here in this thread, and then pick the top three.

We'll send those three questions to the HH Organizers list, as well as propose it as an item for the new HH weekly newsletter. 

We could obviously send it to our own chapters too, or event discuss it at upcoming socials and meet-ups! ;)

But, to start: post your question(s) here before next Wednesday.

cc @thomaswilburn @burtherman @monkeycycle

**Comment by thomaswilburn** [comment]
"What common resources do you wish the H/H website offered to you as an organizer? As a user? What do you _not_ need the national website to include?"

**Comment by thomaswilburn** [comment]
Alternately: "What were you looking for the last time that you visited the national H/H website?"

**Comment by burtherman** [comment]
What would be the most helpful resource for you to organize your local group?

**Comment by burtherman** [comment]
How might we best create more openness and transparency between all Hacks/Hackers groups around the world?

**Comment by burtherman** [comment]
How can we enable you to organize locally while also being part of something larger?

**Comment by Cromian** [comment]
Just listing a series of questions I think we should be asking overtime, but if I were to pick one it would be: 
- Did you know there is a national Hacks Hackers website? 

For me I actually found out about Hacks/Hackers through meetup and never used the website

**Other questions we may want to have on hand:**
- How did you find out about Hacks Hackers?
- When you first went to the site what were you looking for? Did you find it?
- What kind of information would you like the site to include?
- What should we remove/change?
- If you were to re-create the website from scratch, what would that look like? (features, design, language)
- What is the main way you find out about Hacks Hackers events? (have them list it on the form so we know what are all of our information channels)
- Does your chapter have or use a resource hub?

**Comment by monkeycycle** [comment]
I think the most important question is why they came to the site and what they were expecting. 

What are  there needs?
Were they looking for general H/H info, resources, a connection to the local chapter, events listing.

**Comment by MattCarroll** [comment]
Is there a single project that a number of chapters could work on together? Or could we pick up a cool topic and have all the chapters meetup on that topic on the same night?

**Comment by phillipadsmith** [comment]
@thomaswilburn @Cromian @monkeycycle @MattCarroll @burtherman These are great ideas & _amazing_ thinking! :100: 

My gratitude for prioritizing this task. :bow: 

I'll combine these together and we can have a quick vote to determine the top questions, and then discuss next steps.

Phillip.
