### ISSUE TITLE
Time to vote on the questions [Due: Monday, October 5]

### ISSUE THREAD

**Issue by phillipadsmith** [hackshackers/action-group-website#3]
Okay Team! :) 

Let's narrow down the list  of questions from 13 to just three. 

Please pick your top three choices, in order of preference here: https://hackshackers.wufoo.com/forms/hackshackers-website-survey-question-candidates/

**Remember**: Our aim is to solicit community input that will help guide our recommendations to the H/H board, as well as back to the community, on the question of investing resources -- if they should be invested, how they should be invested, etc. -- into improving the hackshackers.com Web property.

Vote now! https://hackshackers.wufoo.com/forms/hackshackers-website-survey-question-candidates/ 

cc @hackshackers/action-group-website

**Comment by phillipadsmith** [comment]
cc @burtherman

**Comment by Cromian** [comment]
@phillipadsmith what kind of results do we have?

**Comment by phillipadsmith** [comment]
@Cromian Thank you for the follow-up! :+1:  On my list to post the results today...

**Comment by phillipadsmith** [comment]
Underwhelming response, but here's the data! :-)
https://github.com/hackshackers/action-group-website/blob/master/surveys/Hacks-Hackers-Website-Survey-Question.csv

I can follow-up with a few proposals to move us forward ASAP (today, or Friday), or anyone should feel free to jump in.

cc @hackshackers/action-group-website
