### ISSUE TITLE
Who would like to report back on Tuesday's open call (October 6, 2015)?

### ISSUE THREAD

**Issue by phillipadsmith** [hackshackers/action-group-website#4]
Per Burt's note today:

> Firstly, we would like hear back from the four committees that formed from the last call, for vision/mission, governance, website and communication. Please send me an email directly with who will be reporting back for your committee.

... I am wondering who would like to report back on our work?

Which of you will be on the call on Tuesday? 

Ideally, it would be great to have someone other than me report back! ;)

Thanks!

Phillip.

cc @hackshackers/action-group-website

**Comment by thomaswilburn** [comment]
Unfortunately I'm in meetings all day this Tuesday, so I'll have to pass.

**Comment by Cromian** [comment]
Sure I can do that. 

---

Misha Vinokur
@Openreporter
www.openreporter.org

```
_____________________________
```

**Comment by phillipadsmith** [comment]
@Cromian Thanks! :+1:
