### ISSUE TITLE
[Input requested. Due Oct 20] Survey to members

### ISSUE THREAD

**Issue by phillipadsmith** [hackshackers/action-group-website#7]
So, based on our internal survey (us + organizers on the open call), it looks like these are three important questions to ask members (in no specific order):
- What would be the most helpful resource for you to organize your local group?
- Why did you visit hackshackers.com, and what were were expecting? **OR** When you first went to the site what were you looking for? Did you find it? (basically, the same question)
- How can ~~we~~ the hackshackers.com website enable you to organize locally while also being part of something larger?

This is by no means a "conclusive" subset of our original questions, and yet I'm A) keen to know if you all think this will provide the input we need to move closer to a plan / proposal and B) if you think there are other questions that we should really prioritize (as these three are somewhat similar)?

Your comments by next Tuesday, Oct 20th if possible. If we can find agreement on the questions, a survey could be circulated to 1000 global H/H members in next week's newsletter. 

cc @hackshackers/action-group-website

**Comment by thomaswilburn** [comment]
I think 1 and 3 are basically the same question. It's not clear to me that being part of a larger group is necessarily something people want from H/H, but I could be totally wrong.

Either way, these look good to me. I'm more interested in the first visit question, as opposed to the "why did you visit?" Once someone gets to their local chapter, repeat visits may not be something we're worried about as the national site.

**Comment by Cromian** [comment]
Agree perhaps we slim it down to two questions?
What would be the most helpful resource for you to organize your local group?Why did you visit hackshackers.com, and what were were expecting?I think they sum up a good starting point. 

```
_____________________________
```

**Comment by burtherman** [comment]
Maybe the last question isn't quite the best phrasing as "being part of a larger group" (I wrote it so self criticizing here). My point was more to get at what people might see as benefits of being part of a broader group, like a global directory, job postings, help forums, etc. and whether that would be of interest

**Comment by phillipadsmith** [comment]
> Agree perhaps we slim it down to two questions?

Good point. Less is more. :-)

> My point was more to get at what people might see as benefits of being part of a broader group, like a global directory, job postings, help forums, etc. and whether that would be of interest

And yet --  taking Burt's comment into consideration -- it sounds like we could boil it down to these three questions:
1. Why did you **first** visit hackshackers.com? What were were expecting? Did you find what you were looking for?
2. What would be the most helpful resource for you to organize your local group?
3. Do you consider being involved in a Hacks/Hackers chapter an opportunity to be involved in something larger? Are there resources that would help you personally take advantage of the size and reach of the Hacks/Hackers network?

Does that sum it up? 

If so, I would be happy to put that into a Google form / Wufoo form and get it out to the organizers list early next week.

**Comment by phillipadsmith** [comment]
> If so, I would be happy to put that into a Google form / Wufoo form and get it out to the organizers list early next week.

Here's our survey:
https://docs.google.com/forms/d/1M67eHcLOdy9tMl2afW6NkB9ANk5W4loaf5RF3ymKAVU/viewform

I'll prep an e-mail to go out about this ASAP. 

I've asked Julia to highlight it in next week's newsletter (there's already another survey in this week's).

**Comment by phillipadsmith** [comment]
E-mail sent! :)
