### ISSUE TITLE
Review Website survey data & present to call

### ISSUE THREAD

**Issue by phillipadsmith** [hackshackers/action-group-website#9]
Last-minute request for the @hackshackers/action-group-website: 

We've received LOTS of responses to the Website survey:
https://docs.google.com/spreadsheets/d/1TwBPhjRVXI1HbgQU9L62MSz02YOPDYWhW8pbzyBllkE/edit?usp=sharing  (46 and counting).

I have not had time to review the most recent 25 responses, and won't have time before tomorrow's call.

Does anyone have capacity to review them today and provide a summary tomorrow? 

If not, we'll push to next month's call in terms of presenting. (That said, we should schedule another conversation to discuss the data & next steps ASAP!)

Phillip.

**Comment by Cromian** [comment]
Sorry tonight is our big deploy. So I'll be a bit preoccupied. 

---

Misha Vinokur
@Openreporter
www.openreporter.org

On Mon, Nov 2, 2015 at 1:01 PM -0800, "Phillip Smith" notifications@github.com wrote:

Last-minute request for the @hackshackers/action-group-website: 

We've received LOTS of responses to the Website survey:

https://docs.google.com/spreadsheets/d/1TwBPhjRVXI1HbgQU9L62MSz02YOPDYWhW8pbzyBllkE/edit?usp=sharing  (46 and counting).

I have not had time to review the most recent 25 responses, and won't have time before tomorrow's call.

Does anyone have capacity to review them today and provide a summary tomorrow? 

If not, we'll push to next month's call in terms of presenting. (That said, we should schedule another conversation to discuss the data & next steps ASAP!)

Phillip.

**Comment by Cromian** [comment]
@phillipadsmith I should have some time tomorrow if you still need help.

**Comment by phillipadsmith** [comment]
@Cromian Yes please! :-)

**Comment by Cromian** [comment]
@phillipadsmith following global call. Need assistance with the presentation?

**Comment by phillipadsmith** [comment]
Yes please! :)

**Comment by Cromian** [comment]
@hackshackers/action-group-website [here is a link](https://docs.google.com/document/d/11g7NWItwZexOiifow1N3FvXhbskDXcKaRIatWXFkCCI/edit) to the draft to present on the call. Feedback welcomed.
